chat_words_dict = {
    "brb": "Be Right Back",
    "lol": "Laugh Out Loud",
    "rofl": "Rolling On the Floor Laughing",
    "omg": "Oh My God",
    "ttyl": "Talk To You Later",
    "idk": "I Don’t Know",
    "smh": "Shaking My Head",
    "imo": "In My Opinion",
    "imho": "In My Humble Opinion",
    "fyi": "For Your Information",
    "btw": "By The Way",
    "nvm": "Never Mind",
    "tbh": "To Be Honest",
    "gtg": "Got To Go",
    "bff": "Best Friends Forever",
    "jk": "Just Kidding",
    "ttfn": "Ta-Ta For Now",
    "yolo": "You Only Live Once",
    "afk": "Away From Keyboard",
    "irl": "In Real Life",
    "dm": "Direct Message",
    "pm": "Private Message",
    "gg": "Good Game",
    "ftw": "For The Win",
    "ppl": "People",
    "thx": "Thanks",
    "lmao": "Laughing My Ass Off",
    "icymi": "In Case You Missed It",
    "fomo": "Fear Of Missing Out",
    "omw": "On My Way",
    "idc": "I Don’t Care",
    "asap": "As Soon As Possible",
    "b/c": "Because",
    "cul8r": "See You Later",
    "gr8": "Great",
    "k": "Okay",
    "l8r": "Later",
    "np": "No Problem",
    "tmi": "Too Much Information",
    "ty": "Thank You",
    "yw": "You’re Welcome",
    "wtf": "What The Fuck",
    'u': 'you',
    'ur': 'your',
    'r': 'are',
    'b4': 'before',
    'bday': 'birthday',
    'plz': 'please',
    'cuz': 'because',
    'msg': 'message',
    'wanna': 'want to',
    'gonna': 'going to'
}